merge from wix fork
davidbyttow/govips pull request #220
Opened 2021-11-15 12:33 UTC by alon-ne

2021-11-22 20:31 UTC, tonimelisma commented
Oh, a lot of good stuff here. I also see there's two other PRs. Let me know when they're ready to review/merge.

And thanks so much for the contributions! You rock! <3

2021-11-22 22:39 UTC, alon-ne commented
If you're up for the task, I'd be glad if you could review this big PR (It also includes the webp ICC fix in the other PR).
Or, if you prefer, I and @Elad-Laufer can break it into a few smaller PR's. Other than being happy to contribute, once this is merged we won't have to maintain our own fork for Wix production code and that would make our lives easier.
So tell me which way would be easier for you. Thanks!

2021-11-23 20:51 UTC, tonimelisma requested changes
The changes look great. Thanks again a lot for the great contributions! Is it possible you summarise new functionality with a couple of bullet points so I can create a new release?

For InterpretationGB16 I know we need to be backwards compatible but if it's a typo maybe we can forget about it? Please see https://github.com/davidbyttow/govips/pull/181

It would be interesting to also get your thoughts on the recent developments and possible future architecture for govips. What are your thoughts on the loading parameters, animated GIFs, and the recent work on moving to `vips_object_set` which was done in PR #170?

Also, do you have any views on the discussion we had with David on issue #164? I suppose there's little value in refactoring the code.

2021-11-23 20:51 UTC, tonimelisma commented on examples/jpeg/example_mozjpeg_image.go
> -	"github.com/davidbyttow/govips/v2/vips"
I don't know how to keep the module paths separate. Can you use `replace` in go.mod? What can we do?

2021-11-23 20:51 UTC, tonimelisma commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Is this file relevant? Perhaps we can drop it from the PR

2021-11-23 20:51 UTC, tonimelisma commented on vips/color.go
> +	InterpretationGB16      Interpretation = C.VIPS_INTERPRETATION_RGB16
Should this be `InterpretationRGB16`

2021-11-23 20:56 UTC, tonimelisma commented
One final point: I think it's cool if we bump libvips and/or go version requirement, but can you also update the README correspondingly?

2021-11-24 10:35 UTC, Elad-Laufer commented
> One final point: I think it's cool if we bump libvips and/or go version requirement, but can you also update the README correspondingly?

Yes it is

2022-01-01 14:19 UTC, davidbyttow commented
Closing as per our conversation in email. Please do continue to send PRs from https://github.com/wix-incubator/govips-contrib and I will have a look!

2022-01-01 14:19 UTC, closed without merging